#################### default parameters ############################
logo = "images/logo.svg"
logo_white = "images/logo-white.svg"
logo_width = "300x"
favicon = "images/favicon.png"
# Meta data
description = "Baking your emotions with cookies"
author = "Chipz Bakery"
og_image = "/images/placeholder.jpg"
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "hello@chipz.cc"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# custom script on header
custom_script = ""
# search
search = true
# widget
widgets = ["suscribe", "recommended", "categories", "about"]
# main sections
mainSections = ["articles"]
# page not found image
page_not_found_image = "images/404.png"

# Preloader
[preloader]
enable = false
preloader = "images/preloader.png" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
